# Generated by Django 2.2 on 2020-07-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boardingday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('icao_code', models.CharField(max_length=255)),
                ('pct_utilization_usedseats', models.FloatField()),
                ('avg_utilization_usedseats', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='boardinghour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('avg_utilization_usedseats', models.FloatField()),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('icao_code', models.CharField(max_length=255)),
                ('pct_utilization_usedseats', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='cbavgday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('icao_code', models.CharField(max_length=255)),
                ('avg_opr_allconveyorbelts', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='cbavghour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('avg_opr_allconveyorbelts', models.FloatField()),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('icao_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='cbperutilday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('cb_id', models.CharField(max_length=255)),
                ('pct_opr_eachconveyorbelt', models.FloatField()),
                ('date', models.DateField()),
                ('icao_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='cbperutilhour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('icao_code', models.CharField(max_length=255)),
                ('cb_id', models.CharField(max_length=255)),
                ('pct_opr_eachconveyorbelt', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='kioskday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('icao_code', models.CharField(max_length=255)),
                ('pct_utilization_day', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='kioskpeakperiod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('icao_code', models.CharField(max_length=255)),
                ('hour', models.IntegerField()),
                ('num_of_visits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='parkavgduration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('icao_code', models.CharField(max_length=255)),
                ('slotid', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='parkday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('icao_code', models.CharField(max_length=255)),
                ('available_slots', models.IntegerField()),
                ('pct_occupied_slots', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='parkhour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('icao_code', models.CharField(max_length=255)),
                ('hour', models.IntegerField()),
                ('available_slots', models.IntegerField()),
                ('pct_occupied_slots', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='parkpeakperiod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('icao_code', models.CharField(max_length=255)),
                ('hour', models.IntegerField()),
                ('used_slots', models.IntegerField()),
                ('maxused_time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='snareautilday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('areaid', models.CharField(max_length=255)),
                ('pct_areawise_util', models.FloatField()),
                ('date', models.DateField()),
                ('icao_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='snareautilhour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('areaid', models.CharField(max_length=255)),
                ('pct_areawise_util', models.FloatField()),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('icao_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='snmaxconsume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('icao_code', models.CharField(max_length=255)),
                ('max_dispenses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sntotalconsumeday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('icao_code', models.CharField(max_length=255)),
                ('total_dispenses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sntotalconsumehour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('icao_code', models.CharField(max_length=255)),
                ('total_dispenses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='trolleycalcday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('pct_utilization_usedtrolley', models.FloatField()),
                ('icao_code', models.CharField(max_length=255)),
                ('unused_trolleys', models.IntegerField()),
                ('used_trolleys', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='trolleycalchour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('icao_code', models.CharField(max_length=255)),
                ('pct_utilization_usedtrolley', models.FloatField()),
                ('unused_trolleys', models.IntegerField()),
                ('used_trolleys', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='wifiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('avg_utilization', models.FloatField()),
                ('date', models.DateField()),
                ('icao_code', models.CharField(max_length=255)),
                ('total_download', models.FloatField()),
                ('total_upload', models.FloatField()),
                ('total_used_minutes', models.IntegerField()),
                ('total_users', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='wifihour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('avg_utilization', models.FloatField()),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('icao_code', models.CharField(max_length=255)),
                ('total_download', models.FloatField()),
                ('total_upload', models.FloatField()),
                ('total_used_minutes', models.IntegerField()),
                ('total_users', models.IntegerField()),
            ],
        ),
    ]
