# Generated by Django 2.2 on 2020-07-19 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_facility_support_userairport'),
    ]

    operations = [
        migrations.CreateModel(
            name='airportfacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('air', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.airport')),
                ('fac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.facility')),
            ],
        ),
    ]
