# Generated by Django 2.2 on 2020-07-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_airportfacility'),
    ]

    operations = [
        migrations.CreateModel(
            name='threshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.TextField(max_length=20)),
                ('threshold_type', models.TextField(max_length=30)),
                ('threshold_value', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('airfac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.airportfacility')),
            ],
        ),
    ]
