# Generated by Django 2.2 on 2020-07-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='type',
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
