# Generated by Django 2.2 on 2020-07-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_airport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='category',
            field=models.TextField(default='NULL', max_length=50),
        ),
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(default='NULL', max_length=10),
        ),
    ]
