# Generated by Django 2.2 on 2020-07-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200726_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(default='NULL', max_length=10, unique='false'),
        ),
    ]
