# Generated by Django 2.2 on 2020-07-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200726_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='category',
            field=models.TextField(default='000', max_length=50),
        ),
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(default='000', max_length=10, unique='false'),
        ),
    ]
