# Generated by Django 2.2 on 2020-07-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200726_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(blank='true', default='000', max_length=10),
        ),
    ]
