# Generated by Django 2.2 on 2020-07-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200727_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
