# Generated by Django 2.2 on 2020-07-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200727_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(blank='True', max_length=10, null='True'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='icao_code',
            field=models.CharField(max_length=10, unique='True'),
        ),
    ]
