# Generated by Django 2.2 on 2020-08-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200803_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threshold',
            name='threshold_type',
        ),
        migrations.AddField(
            model_name='threshold',
            name='sensor_threshold',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='threshold',
            name='capacity',
            field=models.IntegerField(null='True'),
        ),
    ]
